from sqlmodel import Session, select
from .. import models

def get_user_by_username(db: Session, username: str) -> models.User:
    """
    Retrieves a user from the database by username.

    Args:
        db: The database session.
        username: The username to search for.

    Returns:
        The user object if found, otherwise None.
    """
    return db.exec(select(models.User).where(models.User.username == username)).first()

def create_user(db: Session, username: str) -> models.User:
    """
    Creates a new user in the database.

    Args:
        db: The database session.
        username: The username of the new user.

    Returns:
        The newly created user object.
    """
    db_user = models.User(username=username)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

def create_chat_log(db: Session, user_id: int, user_query: str, anonymized_query: str, intent: str, entities: dict, response: str) -> models.ChatLog:
    """
    Creates a new chat log entry in the database.

    Args:
        db: The database session.
        user_id: The ID of the user who initiated the chat.
        user_query: The original user query.
        anonymized_query: The anonymized version of the user query.
        intent: The predicted intent of the user query.
        entities: The extracted entities from the user query.
        response: The response generated by the chatbot.

    Returns:
        The newly created chat log object.
    """
    db_chat_log = models.ChatLog(
        user_id=user_id,
        user_query=user_query,
        anonymized_query=anonymized_query,
        intent=intent,
        entities=entities,
        response=response,
    )
    db.add(db_chat_log)
    db.commit()
    db.refresh(db_chat_log)
    return db_chat_log
